### ISSUE TITLE
Tests don't seem to be running now

### ISSUE THREAD

**Issue by rfay** [ddev/github-action-add-on-test#10]
I saw that tests on this were running on push earlier, but they don't seem to be running now.  The nightlies do seem to be running.

**Comment by julienloizelet** [comment]
I think this is still working (my last push triggered a test action).

Maybe you saw a commit with only markdown modification : it won't trigger the test if there is only markdown modification: https://github.com/ddev/github-action-add-on-test/blob/main/.github/workflows/add-on-simple-tests.yml#L6-L7

**Comment by rfay** [comment]
That makes sense.

**Comment by rfay** [comment]
I guess there must be too many things excluded from tests? 

Reopening, since neither of these are running:

* https://github.com/ddev/github-action-add-on-test/pull/15
* https://github.com/ddev/github-action-add-on-test/pull/13
