### ISSUE TITLE
Keep alive step failed if the branch is protected

### ISSUE THREAD

**Issue by julienloizelet** [ddev/github-action-add-on-test#25]
Since the `1.2.0` release of the `gautamkrishnar/keepalive-workflow`, the "keep alive" step failed if the branch is protected (which is a common practice, I guess), even if we set the `permission: write` directive.

I opened an issue for this: https://github.com/gautamkrishnar/keepalive-workflow/issues/20

As a workaround, I think we could always pass the new `auto_write_check` to `false`.

**Comment by tyler36** [comment]
Just got notified that "ddev-browser" stable test failed; seems to be this.

**Comment by julienloizelet** [comment]
The keep alive action has been fixed with a new [1.2.2 release](https://github.com/gautamkrishnar/keepalive-workflow/releases/tag/1.2.2).

Default value of the new `auto_write_check` has been changed to false to avoid breaking change.

Thus, it should work again ([worked for me](https://github.com/julienloizelet/ddev-playwright/actions/runs/7538376945)) and we don't have to change anything.

**Comment by tyler36** [comment]
Confirmed. ddev-browsersync now working.

Thank you.
