### ISSUE TITLE
Enable test grouping and segregation so release tests aren't run on PRs

### ISSUE THREAD

**Issue by seebeen** [ddev/github-action-add-on-test#30]
On ddev/ddev-minio#39 @rfay talked a bit about reorganizing and segregating tests and he suggested I open an issue and maybe do a PR.

Currently - this action **always** runs both local and repository tests.

https://github.com/ddev/github-action-add-on-test/blob/2c0f0b27d97636e443b8e1a8677c885f77497dff/action.yaml#L97-L107

It doesn't track the test context.
For PRs and pushes, there is no need to test pulling from the repo, and on a scheduled test - there is no need to test locally.

A while back I made my own action which (even with some other problems) has test grouping - which works. So there is no test doubling.

https://github.com/oblakstudio/action-test-ddev-addon/blob/2c92790b7b6e47d85b5b9f09a440800c1c35c404/action.yml#L71-L83

Can we implement something similar here. Addon template can also be improved so it uses test grouping.

Changes are minimal, and they would halve the test execution time.

P.S. I'm more than willing to submit a full PR for the functionality

**Comment by rfay** [comment]
I'd love to see it *not* run the release test on PRs. (only test the current code)

For ordinary testing (nightly, etc) I think the double testing is great.

**Comment by rfay** [comment]
Updated title, looking forward to this improvement. We don't need to run release tests on PRs.

**Comment by tyler36** [comment]
Just came across this issue with ddev-php-dumper. 

A PR "fixed" the issue and the "install from directory" test passed. But it also ran "install from release" which didn't include the fix and therefore failed (as expected).

I saw on [SO](https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow) ways to get the PR number. If we passed that through, would "bats" be able to get it and then act accordingly?

**Comment by julienloizelet** [comment]
Hey @tyler36,

I think that we don't need to get the PR number to solve this issue (but maybe you want to retrieve it for a specific scenario ?).

If I understand correctly, we want to exclude "release" test on PR.

I guess one way to do this is : 


1) be able to detect if we are on a PR triggered run: For this, we should be able to use a `github.event_name == 'pull_request'` condition somewhere
2) be able to run only specific bats tests: here, the [tag feature ](https://bats-core.readthedocs.io/en/stable/writing-tests.html#tagging-tests) coupled with the [--filter-tags](https://bats-core.readthedocs.io/en/stable/writing-tests.html#filtering-execution) bats argument, could be a good option.


For example, if we assume that add-on maintainers tag their tests with "release" tag and a "head" tag (we may have to decide which naming is appropriate): 

```
# bats test_tags=head
@test "install from directory" {
  # ...
}

# bats test_tags=release
@test "install from release" {
  # ...
}
```

I see at least 2 options:

## Option 1

We could modify the action with something like: 


```
- name: Run test
      if ${{ github.event_name == 'pull_request') 
      shell: bash
      run: cd ${{ inputs.addon_path }} && bats tests --filter-tags head
     
     ( or bats tests --filter-tags !release)

- name: Run test
      if ${{ github.event_name != 'pull_request') 
      shell: bash
      run: cd ${{ inputs.addon_path }} && bats tests

```


The main issue here is that is a breaking change: people who don't have tagged their test with the appropriate tag names won't have any tests running on PR.

## Option 2

An other option could be a new optional input "bats_arguments".
It should be a non breaking change but a bit more complicated for final user.

Here, we'll just have to handle this new optional input (empty string by default).

Maybe we could add a new step to create the BATS_ARGUMENTS env variable: 

```
- name: Set BATS_ARGUMENTS env
        shell: bash
        run:  echo "BATS_ARGUMENTS=${{ inputs.bats_arguments }} " >> $GITHUB_ENV
```

And then use it it the related step: 

```
 - name: Run test
 
      shell: bash
      run: cd ${{ inputs.addon_path }} && bats tests ${{env.BATS_ARGUMENTS}}

```

But there will be more change for each maintainer on their add-on: 

They will have to : 
1) tags their tests with "release", "head" or whatever they want
2) Modify their action to send the correct BATS_ARGUMENTS input: 

```

-steps
  - name: Set BATS_ARGUMENTS env
    run: |
      if [ "${{ github.event_name }}" == "pull_request" ]; then
        echo "BATS_ARGUMENTS=--filter-tags head" >> $GITHUB_ENV
      else
        echo "BATS_ARGUMENTS=" >> $GITHUB_ENV
      fi
    
   - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
          bats_arguments: ${{env.BATS_ARGUMENTS}}
    
```   




---

For me, option 2 is better: it is more generic as an user will be able to pass any bats arguments (not only the filter tags).

But in all case, it will imply some modifications for all add-ons.

Please let me know what you think.

Thanks

**Comment by tyler36** [comment]
Thank you for thoughtful consideration. 

In my case, there's only a single test case I want to skip "install from release".
Is there a way bats can exclude by name? 

"Exclude by tag" would also work for me and require less changes for addon developers.

**Comment by julienloizelet** [comment]
> 
> Is there a way bats can exclude by name?
> 

It appears that a `--filter <regex>` argument can be used to filter by name: https://bats-core.readthedocs.io/en/stable/usage.html

Thanks

**Comment by tyler36** [comment]
would be interesting in hearing @stasadev  ideas too!

@rfay is at DrupalCon at the moment so is busy busy busy

**Comment by julienloizelet** [comment]
> The problem is it's not bats that's doing DDEV HEAD vs stable.
> 
> Those are a matrix of github workflows. Nothing to do with bats.
> 
> What we need to do is have a way to disable one of the workflows conditionally.

Excluding "head" or "stable" in the matrix, if we detect that the flow has been triggered by a pull request is already possible in the add-on workflow.

For example, if one want to exclude "stable" test for pull request, the strategy directive should be change to something like: 

```
strategy:
  matrix:
    ddev_version:
      - stable
      - HEAD
    exclude:
      - ddev_version: ${{ github.event_name == 'pull_request' && 'stable' }}
```


But I thought the initial problem was to find a way to exclude "test from release" on a pull request : 

> I'd love to see it not run the release test on PRs. (only test the current code)

> We don't need to run release tests on PRs.

and this is related to bats tests: https://github.com/ddev/ddev-addon-template/blob/main/tests/test.bats#L36

Thanks

**Comment by stasadev** [comment]
> ## Option 1
> We could modify the action with something like:
> 
> ```
> - name: Run test
>       if ${{ github.event_name == 'pull_request') 
>       shell: bash
>       run: cd ${{ inputs.addon_path }} && bats tests --filter-tags head
>     
>      ( or bats tests --filter-tags !release)
> 
> - name: Run test
>       if ${{ github.event_name != 'pull_request') 
>       shell: bash
>       run: cd ${{ inputs.addon_path }} && bats tests
> ```
> 
> The main issue here is that is a breaking change: people who don't have tagged their test with the appropriate tag names won't have any tests running on PR.

@julienloizelet, I tested this option with `bats tests --filter-tags '!release'` and it runs all the tests (even without tags) excluding this test:

```
# bats test_tags=release
@test "install from release" {
```

It's not a breaking change, I like it, people can just add `# bats test_tags=release` to certain tests whenever they want, and we can add this tag by default in the [ddev-addon-template](https://github.com/ddev/ddev-addon-template/blob/c7ae2776d0e9047817296f16b0063bb3909d27e1/tests/test.bats#L36).

**Comment by julienloizelet** [comment]
@stasadev , thanks for testing!

In fact, option 1 with `bats tests --filter-tags '!release'` should be enough to solve the problem, and it's not a breaking change, as you've noticed.

But, while it may be a bit of "over-engineering", I think allowing a user to have full control over the test command could be a good improvement.

That's why I'm thinking of an "option 3":

- by default, the launched command during the "Run test" step will be 
    - `bats tests --filter-tags '!release'`  on pull request workflow
    - `bats tests` on any other workflow
- There will be a new optional entry `tests_command` (empty string by default) and if this entry is not empty, it will be used to launch the command. 

With this, people will be able to define the test command they want, and it will be up to them to define the right command for PR, push or whatever workflow they're using. But by default, it will be like the Option 1.

What do you think ?

Thanks

**Comment by stasadev** [comment]
> * There will be a new optional entry `tests_command` (empty string by default) and if this entry is not empty, it will be used to launch the command.

This is a solid option, I like it. It will give maintainers full control over what they want to run with `bats`.

**Comment by julienloizelet** [comment]
> This is a solid option, I like it. It will give maintainers full control over what they want to run with `bats`.

Ok! I will try to work on it asap.

Thanks

**Comment by rfay** [comment]
Looks awesome, thanks!
