### ISSUE TITLE
Exclude also "release" tagged test for "push" workflows

### ISSUE THREAD

**Issue by julienloizelet** [ddev/github-action-add-on-test#37]
Since this [release 2.1.0](https://github.com/ddev/github-action-add-on-test/releases/tag/v2.1.0),

we are not running "release" tagged tests on "pull request" triggered workflow.

This is great.

But shouldn't we also disable "release" tagged test on push ?

If a PR is merged, of if a direct push is done, the "release" tagged tests may failed (as the last release does not contain last commit added by the merge/push) 

This is what happened to me with the redis-commander add-on: 
- I create a PR to add a new command, and this PR included new test for this command
- It was great that test was not run for the release tags (because it will have failed due to the missing new command)

But, then, I merged and this has triggered a "push" workflow , and [release tagged tests failed](https://github.com/ddev/ddev-redis-commander/actions/runs/11495550691)...

By definition, something that just has been pushed is not yet released, so why should we test it against the released code ?

What do you think ?

Thanks!

**Comment by rfay** [comment]
Makes sense to me! Thanks so much for maintaining this!
